In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys

sys.path.append("../")

In [2]:
df = pd.read_csv("../data/processed/cleaned_data.csv")

df.head()

C:\Users\hp\AppData\Local\Temp\ipykernel_4556\2697200141.py:1: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/cleaned_data.csv")

,Unnamed: 0,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,0,145249,12827,2015-03-01,True,,Close Corporation,Mr,English,First National Bank,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,1,145249,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,2,145249,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,3,145255,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,4,145255,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [4]:
from src.hypothesis.ab_testing import HypothesisTester

# Filter only Male and Female
df_gendered = df[df["Gender"].isin(["Male", "Female"])]
tester = HypothesisTester(df_gendered)

# Run all 6 tests
print(tester.test_claim_frequency_chi2("Gender"))
print(tester.test_high_severity_chi2("Gender"))
print(tester.test_negative_margin_chi2("Gender"))

print(tester.test_claim_severity_ttest("Gender"))
print(tester.test_margin_difference_ttest("Gender"))
print(tester.test_total_premium_ttest("Gender"))

{'method': 'chi-squared', 'target': 'Has Claim', 'groups': ['Male', 'Female'], 'stat': np.float64(0.003704891861036439), 'p': np.float64(0.9514644755420456)}
{'method': 'chi-squared', 'target': 'High Severity', 'groups': ['Male', 'Female'], 'stat': 0.0, 'p': 1.0}
{'method': 'chi-squared', 'target': 'Negative Margin', 'groups': ['Male', 'Female'], 'stat': np.float64(28.29057327375584), 'p': np.float64(1.0440317576517565e-07)}
{'method': 't-test', 'target': 'Claim Severity', 'groups': ['Male', 'Female'], 'stat': np.float64(-0.5790202780038484), 'p': np.float64(0.5680286951630673)}
{'method': 't-test', 'target': 'Margin', 'groups': ['Male', 'Female'], 'stat': np.float64(-0.21120818486711093), 'p': np.float64(0.8327288884508434)}
{'method': 't-test', 'target': 'Total Premium', 'groups': ['Male', 'Female'], 'stat': np.float64(-4.294841634078025), 'p': np.float64(1.7677891662019326e-05)}

In [10]:
#provinces gauteng vs northern cape(highest loss ration vs low loss ratio)
# Filter only Male and Female
df_provinces = df[df['Province'].isin(["Gauteng", "Northern Cape"])]
tester = HypothesisTester(df_provinces)

# Run all 6 tests
print(tester.test_claim_frequency_chi2("Province"))
print(tester.test_high_severity_chi2("Province"))
print(tester.test_negative_margin_chi2("Province"))

print(tester.test_claim_severity_ttest("Province"))
print(tester.test_margin_difference_ttest("Province"))
print(tester.test_total_premium_ttest("Province"))

{'method': 'chi-squared', 'target': 'Has Claim', 'groups': ['Gauteng', 'Northern Cape'], 'stat': np.float64(7.757473688986979), 'p': np.float64(0.00534907280471951)}
{'method': 'chi-squared', 'target': 'High Severity', 'groups': ['Gauteng', 'Northern Cape'], 'stat': 0.0, 'p': 1.0}
{'method': 'chi-squared', 'target': 'Negative Margin', 'groups': ['Gauteng', 'Northern Cape'], 'stat': np.float64(7.962808714595615), 'p': np.float64(0.0047748261617796585)}
{'method': 't-test', 'target': 'Claim Severity', 'groups': ['Gauteng', 'Northern Cape'], 'stat': np.float64(2.9378534649520356), 'p': np.float64(0.01886949988646169)}
{'method': 't-test', 'target': 'Margin', 'groups': ['Gauteng', 'Northern Cape'], 'stat': np.float64(-6.457866249374809), 'p': np.float64(1.1070082066975974e-10)}
{'method': 't-test', 'target': 'Total Premium', 'groups': ['Gauteng', 'Northern Cape'], 'stat': np.float64(7.102512660644079), 'p': np.float64(1.3515631798475534e-12)}

In [12]:
#provinces gauteng vs northern cape(highest loss ration vs low loss ratio)
# Filter only Male and Female
df_provinces = df[df['PostalCode'].isin([1460, 2037])]
tester = HypothesisTester(df_provinces)

# Run all 6 tests
print(tester.test_claim_frequency_chi2("PostalCode"))
print(tester.test_high_severity_chi2("PostalCode"))
print(tester.test_negative_margin_chi2("PostalCode"))

print(tester.test_claim_severity_ttest("PostalCode"))
print(tester.test_margin_difference_ttest("PostalCode"))
print(tester.test_total_premium_ttest("PostalCode"))

{'method': 'chi-squared', 'target': 'Has Claim', 'groups': [1460, 2037], 'stat': np.float64(0.0), 'p': np.float64(1.0)}
{'method': 'chi-squared', 'target': 'High Severity', 'groups': [1460, 2037], 'stat': 0.0, 'p': 1.0}
{'method': 'chi-squared', 'target': 'Negative Margin', 'groups': [1460, 2037], 'stat': np.float64(0.0006365675169031419), 'p': np.float64(0.9798712769777917)}
{'method': 't-test', 'target': 'Claim Severity', 'groups': [1460, 2037], 'stat': np.float64(-4.4727522056333475), 'p': np.float64(0.00045521987409276825)}
{'method': 't-test', 'target': 'Margin', 'groups': [1460, 2037], 'stat': np.float64(2.3884345969381973), 'p': np.float64(0.01698182788819826)}
{'method': 't-test', 'target': 'Total Premium', 'groups': [1460, 2037], 'stat': np.float64(2.089940929054883), 'p': np.float64(0.03676614237613366)}